import React, { useState, useEffect } from "react";
import { 
  MapPin, 
  Phone, 
  Clock, 
  Star, 
  Award, 
  ShieldCheck, 
  Utensils, 
  ChevronRight, 
  Sparkles, 
  Coffee, 
  Heart, 
  MessageSquare, 
  Calendar, 
  Users, 
  CheckCircle, 
  ThumbsUp, 
  Plus, 
  Share2, 
  Navigation, 
  Quote, 
  X, 
  User, 
  MessageCircle,
  ExternalLink
} from "lucide-react";
import { motion, AnimatePresence } from "motion/react";

// Image path generated by AI Studio
const HERO_IMAGE_PATH = "/src/assets/images/south_indian_feast_1781299053985.jpg";

interface MenuItem {
  id: string;
  name: string;
  price: number;
  description: string;
  category: "breakfast" | "meals" | "sweets-beverages";
  tags: string[];
  spiceLevel?: 1 | 2 | 3;
  craftStory: string;
  imageUrl: string;
}

interface Review {
  id: string;
  userName: string;
  rating: number;
  date: string;
  comment: string;
  likes: number;
  verified: boolean;
}

interface Booking {
  id: string;
  guestName: string;
  phone: string;
  guestsCount: number;
  date: string;
  timeSlot: string;
  hallType: "Classic Dining" | "AC Royal Hall";
  specialRequest?: string;
  status: "Confirmed" | "Allocated";
  bookingCode: string;
}

export default function App() {
  // State management
  const [selectedCategory, setSelectedCategory] = useState<string>("all");
  const [selectedMenuItem, setSelectedMenuItem] = useState<MenuItem | null>(null);
  const [orderQuantity, setOrderQuantity] = useState<number>(1);
  const [orderSimulated, setOrderSimulated] = useState<boolean>(false);
  
  // Table Booking State
  const [bookingName, setBookingName] = useState<string>("");
  const [bookingPhone, setBookingPhone] = useState<string>("");
  const [bookingCount, setBookingCount] = useState<number>(2);
  const [bookingDate, setBookingDate] = useState<string>("");
  const [bookingTime, setBookingTime] = useState<string>("12:30 PM");
  const [bookingHall, setBookingHall] = useState<"Classic Dining" | "AC Royal Hall">("Classic Dining");
  const [bookingRequest, setBookingRequest] = useState<string>("");
  const [bookingSuccess, setBookingSuccess] = useState<Booking | null>(null);
  const [allBookings, setAllBookings] = useState<Booking[]>([]);

  // User Review State
  const [reviewName, setReviewName] = useState<string>("");
  const [reviewRating, setReviewRating] = useState<number>(5);
  const [reviewComment, setReviewComment] = useState<string>("");
  const [reviewSuccessMessage, setReviewSuccessMessage] = useState<string>("");
  
  // Initialize existing review database (aligned with 3,914 Google reviews average rating 4.1)
  const [reviewsList, setReviewsList] = useState<Review[]>([
    {
      id: "rev-1",
      userName: "Ranganath K.",
      rating: 5,
      date: "2 days ago",
      comment: "Mahesh Prasad never fails to amaze. Their Mysore Masala Dosa is unparalleled—the perfect texture, golden-crisp on the outside with that rich, authentic red garlic chutney smattered inside. Pair it with their signature zinc brass Filter Coffee. Genuine Mysuru tradition served hot!",
      likes: 42,
      verified: true
    },
    {
      id: "rev-2",
      userName: "Ananya Deshpande",
      rating: 4,
      date: "1 week ago",
      comment: "The South Indian meals here are top tier and extremely budget friendly. The sambar has that authentic, mildly-sweet Mysuru tang. Extremely crowded during afternoon peak hours, but their express seating system is very efficient. Absolute value for money!",
      likes: 29,
      verified: true
    },
    {
      id: "rev-3",
      userName: "Srinivas Gowda",
      rating: 4,
      date: "2 weeks ago",
      comment: "A classic heritage spot in Lakshmipuram near the RTO office. Highly recommend the Rava Idli and crispy Uddin Vada. Golden, fluffy, and served with pure coconut chutney. A must-visit vegetarian institution in Mysuru.",
      likes: 18,
      verified: true
    }
  ]);

  // Overall statistics simulation based on real data: 4.1 rating, 3914 votes
  const [numReviews, setNumReviews] = useState<number>(3914);
  const [avgRating, setAvgRating] = useState<number>(4.1);

  // Load bookings from LocalStorage on mount
  useEffect(() => {
    const stored = localStorage.getItem("mahesh_prasad_bookings");
    if (stored) {
      try {
        setAllBookings(JSON.parse(stored));
      } catch (e) {
        console.error(e);
      }
    }
  }, []);

  // Save booking handler
  const handleBookingSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!bookingName || !bookingPhone || !bookingDate) return;

    const code = "MP-" + Math.floor(100000 + Math.random() * 900000);
    const newBooking: Booking = {
      id: "book-" + Date.now(),
      guestName: bookingName,
      phone: bookingPhone,
      guestsCount: bookingCount,
      date: bookingDate,
      timeSlot: bookingTime,
      hallType: bookingHall,
      specialRequest: bookingRequest,
      status: "Confirmed",
      bookingCode: code
    };

    const updatedBookings = [newBooking, ...allBookings];
    setAllBookings(updatedBookings);
    localStorage.setItem("mahesh_prasad_bookings", JSON.stringify(updatedBookings));

    setBookingSuccess(newBooking);
    
    // Clear inputs after 
    setBookingName("");
    setBookingPhone("");
    setBookingRequest("");
  };

  // Review submission handler
  const handleReviewSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!reviewName || !reviewComment) return;

    const newReview: Review = {
      id: "rev-custom-" + Date.now(),
      userName: reviewName,
      rating: reviewRating,
      date: "Just now",
      comment: reviewComment,
      likes: 0,
      verified: true
    };

    // Calculate new average mathematically to keep it realistic
    const newCount = numReviews + 1;
    const newAvg = parseFloat(((avgRating * numReviews + reviewRating) / newCount).toFixed(2));

    setReviewsList([newReview, ...reviewsList]);
    setNumReviews(newCount);
    setAvgRating(newAvg);
    
    setReviewSuccessMessage("Thank you! Your verified review has been posted successfully.");
    setReviewName("");
    setReviewComment("");

    setTimeout(() => {
      setReviewSuccessMessage("");
    }, 4500);
  };

  // Like a review
  const handleLikeReview = (id: string) => {
    setReviewsList(prev => prev.map(rev => {
      if (rev.id === id) {
        return { ...rev, likes: rev.likes + 1 };
      }
      return rev;
    }));
  };

  // Delete/Cancel booking
  const handleCancelBooking = (id: string) => {
    const filtered = allBookings.filter(b => b.id !== id);
    setAllBookings(filtered);
    localStorage.setItem("mahesh_prasad_bookings", JSON.stringify(filtered));
  };

  // Share action simulation
  const handleShareApp = () => {
    if (navigator.share) {
      navigator.share({
        title: "Mahesh Prasad Veg Restaurant Mysuru",
        text: "Check out Mahesh Prasad, Mysuru's top-rated authentic vegetarian South Indian restaurant!",
        url: window.location.href
      }).catch(console.error);
    } else {
      navigator.clipboard.writeText(window.location.href);
      alert("App page URL copied to clipboard! Share it with your friends.");
    }
  };

  // Menu database
  const menuData: MenuItem[] = [
    {
      id: "menu-1",
      name: "Special Mysore Masala Dosa",
      price: 90,
      description: "Crispy rice crepe smeared with our legendary heritage red chili-garlic paste, stuffed with potato masala and topped with pure ghee.",
      category: "breakfast",
      tags: ["Signature Key", "Pure Ghee roasted"],
      spiceLevel: 2,
      craftStory: "Our Mysore Masala Dosa is crafted using organic black gram and parboiled rice, fermented for exactly 14 hours. The magic lies in our secret red garlic chutney smeared before roasting on hand-adjusted cast iron griddles.",
      imageUrl: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?auto=format&fit=crop&q=80&w=400"
    },
    {
      id: "menu-2",
      name: "Heritage Royal Mysuru Meal (Thali)",
      price: 160,
      description: "A colossal traditional feast: steamed rice, majestic sambar, spicy rasam, seasonal vegetable kootu, poriyal, house pickle, papadum, fresh buttermilk, and Mysore Pak.",
      category: "meals",
      tags: ["Chef Special", "Unlimited Rice Included"],
      spiceLevel: 1,
      craftStory: "Crafted following the royal kitchen traditions of the Wodeyar kings. Our meals bring together balanced nutrition using locally-milled grains and house-ground spice blends (Sambar Masalas).",
      imageUrl: "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?auto=format&fit=crop&q=80&w=400"
    },
    {
      id: "menu-3",
      name: "Heritage Steamed Rava Idli",
      price: 50,
      description: "Large fluffy semolina idli roasted with ghee, mustard seeds, curry leaves, topped with cashew nuts, and served with potato sagu & spicy mint-coconut chutney.",
      category: "breakfast",
      tags: ["Healthy choice", "Pure ghee roasted"],
      spiceLevel: 1,
      craftStory: "Cooked inside pure copper steamers to guarantee that airy, pillowy bounce. Topped with premium roasted cashews and served matching the classic Mysuru RTO-office-lane breakfast legacy.",
      imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&q=80&w=400"
    },
    {
      id: "menu-4",
      name: "Crispy Golden Uddin Vada (2 Pcs)",
      price: 45,
      description: "Crisp, crackling black-grape savory donuts blended with whole black peppercorns, fresh ginger, and curry leaves. Deeply fried to absolute gold perfection.",
      category: "breakfast",
      tags: ["Crispy", "Popular pairing"],
      spiceLevel: 1,
      craftStory: "Hand-whipped for twenty minutes to inject maximum oxygen into the batter, ensuring an incredibly crispy shell on the exterior while remaining soft and feathery inside.",
      imageUrl: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&q=80&w=400"
    },
    {
      id: "menu-5",
      name: "Traditional Brass Filter Coffee",
      price: 35,
      description: "Authentic chicory-infused deep coffee decoction mixed with frotheed whole organic milk, poured iteratively inside traditional brass dabarah for premium cooling and foam.",
      category: "sweets-beverages",
      tags: ["Must Try", "Authentic Decoction"],
      craftStory: "Brewed freshly every hour in our triple-chamber silver steel filter using clean-washed robusta-arabica blend beans locally shade-grown in Coorg hilly estates.",
      imageUrl: "https://images.unsplash.com/photo-1541167760496-1628856ab772?auto=format&fit=crop&q=80&w=400"
    },
    {
      id: "menu-6",
      name: "Royal Ghee Mysore Pak (2 Pcs)",
      price: 80,
      description: "The royal melt-in-mouth traditional sweet of Mysuru city, heavily embedded with hot aromatic ghee, pure chickpea flour, and raw cane sugar.",
      category: "sweets-beverages",
      tags: ["Mysore Heritage", "Sweet Celebration"],
      craftStory: "Our dessert master replicates the famed 1935 palace recipe, utilizing double-clarified hot local farm ghee resulting in those classic honeycomb cavities and legendary aroma.",
      imageUrl: "https://images.unsplash.com/photo-1626132647523-66f5bf380027?auto=format&fit=crop&q=80&w=400"
    },
    {
      id: "menu-7",
      name: "Authentic Bisi Bele Bath",
      price: 80,
      description: "Spicy and tangy rice-lentil porridge boiled with heritage vegetables, toasted cashew nuts, laced with hot pure ghee, and served with crispy mini khara boondi.",
      category: "meals",
      tags: ["Spicy Tangy", "Cozy Food"],
      spiceLevel: 2,
      craftStory: "Seasoned with real nutmeg, kapok buds (marathi moggu), dry red chilies from Byadagi, and fresh copra, cooked slowly in pressure bronze vats.",
      imageUrl: "https://images.unsplash.com/photo-1601050690597-df056fb49785?auto=format&fit=crop&q=80&w=400"
    },
    {
      id: "menu-8",
      name: "Kesari Bhath with Cardamom",
      price: 60,
      description: "Traditional sweet semolina pudding sweetened with raw sugar, heavily roasted in pure ghee, and flavored with green cardamom, roasted raisins, and cashew nuts.",
      category: "sweets-beverages",
      tags: ["Dessert Delight", "Rich Ghee"],
      craftStory: "Flavored naturally without artificial colorings using pure organic saffron strands imported from the high valleys.",
      imageUrl: "https://images.unsplash.com/photo-1505253758473-96b7015fcd40?auto=format&fit=crop&q=80&w=400"
    }
  ];

  const filteredMenuItems = selectedCategory === "all" 
    ? menuData 
    : menuData.filter(item => item.category === selectedCategory);

  return (
    <div className="bg-brand-cream text-brand-dark min-h-screen font-sans antialiased selection:bg-brand-gold/30 selection:text-brand-dark">
      
      {/* Top Banner with Key Highlights */}
      <div className="bg-brand-forest text-brand-cream text-xs py-2 px-4 flex flex-col sm:flex-row justify-between items-center gap-2 border-b border-brand-gold/20 shadow-sm relative z-20">
        <div className="flex items-center gap-4">
          <span className="flex items-center gap-1 font-medium">
            <span className="h-2 w-2 rounded-full bg-emerald-500 animate-pulse"></span>
            Rank #1 Best Family Restaurant in Mysuru
          </span>
          <span className="hidden md:inline-block text-brand-gold">|</span>
          <span className="hidden md:flex items-center gap-1 text-zinc-350">
            <Clock className="w-3.5 h-3.5" /> 6:30 AM – 10:30 PM (Daily)
          </span>
        </div>
        <div className="flex items-center gap-4">
          <span className="flex items-center gap-1 text-brand-gold font-semibold">
            <Star className="w-3.5 h-3.5 fill-brand-gold" /> 4.1 Rating ({numReviews} Reviews)
          </span>
          <a href="tel:08212330820" className="flex items-center gap-1 hover:text-brand-gold transition-colors text-zinc-300">
            <Phone className="w-3.5 h-3.5" /> 0821 233 0820
          </a>
        </div>
      </div>

      {/* Main Elegant Header */}
      <header className="sticky top-0 bg-brand-cream/95 backdrop-blur-md border-b border-brand-gold/10 z-10 py-4 px-4 sm:px-8 shadow-sm">
        <div className="max-w-7xl mx-auto flex justify-between items-center">
          <div className="flex items-center gap-3">
            <div className="bg-brand-forest text-brand-gold h-10 w-10 sm:h-12 sm:w-12 rounded-xl flex items-center justify-center font-serif text-xl sm:text-2xl font-bold shadow-md border border-brand-gold/30">
              M
            </div>
            <div>
              <h1 className="font-serif text-lg sm:text-2xl font-bold tracking-tight text-brand-forest">
                Mahesh Prasad
              </h1>
              <p className="text-[10px] sm:text-xs font-semibold tracking-widest uppercase text-brand-terracotta">
                Veg Restaurant • Mysuru
              </p>
            </div>
          </div>

          {/* Nav Buttons */}
          <nav className="flex items-center gap-3">
            <a 
              href="#menu-section" 
              className="hidden sm:inline-block px-4 py-2 text-sm font-medium text-brand-forest hover:text-brand-terracotta transition-colors"
            >
              Menu
            </a>
            <a 
              href="#reservations" 
              className="hidden md:inline-block px-4 py-2 text-sm font-medium text-brand-forest hover:text-brand-terracotta transition-colors"
            >
              Book Table
            </a>
            <a 
              href="#reviews-section" 
              className="hidden sm:inline-block px-4 py-2 text-sm font-medium text-brand-forest hover:text-brand-terracotta transition-colors"
            >
              Reviews
            </a>
            
            <a 
              href="https://www.google.com/maps/search/?api=1&query_place_id=ChIJ776TqABwrzsRJlFuzZSXo-I&query=Mahesh%20Prasad%20Veg%20Restaurant"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-1 bg-brand-forest/5 hover:bg-brand-forest/10 text-brand-forest px-3.5 py-1.5 sm:px-4 sm:py-2 rounded-xl text-xs sm:text-sm font-medium border border-brand-forest/10 transition-all outline-none"
            >
              <Navigation className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">Directions</span>
            </a>

            <button 
              onClick={handleShareApp}
              className="p-2 bg-brand-cream hover:bg-zinc-100 rounded-xl border border-zinc-200 text-zinc-650 transition-colors"
              title="Share"
            >
              <Share2 className="w-4 h-4" />
            </button>
          </nav>
        </div>
      </header>

      {/* Hero Section */}
      <section className="relative overflow-hidden py-12 sm:py-20 px-4 sm:px-8 border-b border-brand-gold/10">
        <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
          
          <div className="lg:col-span-7 space-y-6">
            <div className="inline-flex items-center gap-2 px-3 py-1 bg-brand-gold/10 border border-brand-gold/30 rounded-full text-brand-terracotta text-xs font-semibold uppercase tracking-wider">
              <Award className="w-4 h-4" /> Ranked #1 Vegetarian Diner in Mysuru
            </div>
            
            <h1 className="font-serif text-3xl sm:text-5xl lg:text-6xl font-bold tracking-tight text-brand-forest leading-[1.1]">
              Authentic Flavors of <span className="text-brand-terracotta italic relative block sm:inline">Mysore Heritage<span className="absolute -bottom-2 left-0 w-full h-1 bg-brand-gold/30 rounded"></span></span>
            </h1>

            <p className="text-base sm:text-lg text-zinc-700 max-w-xl leading-relaxed">
              Experience the royal legacy of traditional South Indian cooking. Famous for crisp hand-poured red garlic <strong className="text-brand-forest font-semibold">Mysore Masala Dosa</strong>, golden vadas, unlimited brass platters, and authentic filter coffee brewed to perfection.
            </p>

            {/* Visual Quick Contact Bar */}
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 border-t border-b border-brand-gold/15 py-6">
              <div className="flex items-start gap-3">
                <div className="p-2.5 bg-brand-cream border border-brand-gold/20 rounded-xl text-brand-terracotta shadow-sm shrink-0">
                  <MapPin className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="font-semibold text-sm text-brand-forest uppercase tracking-wider">Heritage Location</h4>
                  <p className="text-xs text-zinc-600 line-clamp-2 mt-0.5" title="Ballal Cir, Chamarajapuram, Mysuru">
                    Ballal Circle, near RTO Office, Chamarajapura, Mysuru
                  </p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <div className="p-2.5 bg-brand-cream border border-brand-gold/20 rounded-xl text-brand-forest shadow-sm shrink-0">
                  <Phone className="w-5 h-5" />
                </div>
                <div>
                  <h4 className="font-semibold text-sm text-brand-forest uppercase tracking-wider">Call for Quick Orders</h4>
                  <p className="text-xs text-zinc-600 mt-0.5">
                    0821 233 0820 <span className="text-emerald-600 font-medium">(Click-to-call active)</span>
                  </p>
                </div>
              </div>
            </div>

            {/* Quick Action CTAs */}
            <div className="flex flex-wrap items-center gap-4">
              <a 
                href="#menu-section" 
                className="bg-brand-forest hover:bg-brand-forest/90 text-brand-cream border border-brand-gold/40 px-6 py-3.5 rounded-xl font-semibold shadow-lg hover:shadow-xl hover:-translate-y-0.5 transition-all outline-none flex items-center gap-2 group text-sm"
              >
                Explore Royal Menu
                <ChevronRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
              </a>

              <a 
                href="#reservations" 
                className="bg-white hover:bg-zinc-50 text-brand-forest border border-zinc-200 px-6 py-3.5 rounded-xl font-semibold shadow-sm hover:shadow transition-all outline-none text-sm"
              >
                Simulate Reservation
              </a>

              <a 
                href="https://www.google.com/maps/search/?api=1&query_place_id=ChIJ776TqABwrzsRJlFuzZSXo-I&query=Mahesh%20Prasad%20Veg%20Restaurant"
                target="_blank"
                rel="noopener noreferrer"
                className="text-brand-terracotta hover:text-brand-terracotta/80 font-semibold text-sm flex items-center gap-1.5"
              >
                Maps Directions <ExternalLink className="w-4 h-4" />
              </a>
            </div>

            {/* Trust Badges */}
            <div className="flex flex-wrap items-center gap-6 pt-2 text-xs text-zinc-500">
              <span className="flex items-center gap-1">
                <ShieldCheck className="w-4 h-4 text-emerald-600" /> 100% Pure Vegetarian Restuarant
              </span>
              <span className="flex items-center gap-1">
                <Sparkles className="w-4 h-4 text-brand-gold" /> Traditional Royal Recipes
              </span>
              <span className="flex items-center gap-1">
                <Clock className="w-4 h-4 text-zinc-650" /> Ground Zero Fresh Brewing
              </span>
            </div>
          </div>

          {/* Hero Image Block */}
          <div className="lg:col-span-5 relative">
            <div className="absolute inset-0 bg-brand-gold/10 rounded-2xl filter blur-xl transform translate-x-3 translate-y-3"></div>
            
            <div className="relative border-4 border-brand-gold/20 rounded-3xl overflow-hidden shadow-2xl bg-white">
              <img 
                src={HERO_IMAGE_PATH} 
                alt="Traditional South Indian Feast at Mahesh Prasad" 
                className="w-full h-[320px] sm:h-[420px] object-cover hover:scale-105 transition-transform duration-700"
                referrerPolicy="no-referrer"
              />
              
              {/* Overlay elements */}
              <div className="absolute top-4 left-4 bg-emerald-950/90 text-brand-cream border border-brand-gold/30 px-3 py-1.5 rounded-xl text-xs font-semibold flex items-center gap-1.5 backdrop-blur-sm">
                <span className="inline-block w-2.5 h-2.5 rounded-full bg-emerald-500"></span>
                Fresh &amp; Pure Vegetarian
              </div>

              <div className="absolute bottom-4 right-4 bg-brand-dark/90 text-brand-cream p-4 rounded-2xl border border-white/10 max-w-[240px] shadow-lg backdrop-blur-sm">
                <div className="flex items-center gap-1 text-brand-gold text-sm font-bold mb-1">
                  <Star className="w-4 h-4 fill-brand-gold" />
                  <Star className="w-4 h-4 fill-brand-gold" />
                  <Star className="w-4 h-4 fill-brand-gold" />
                  <Star className="w-4 h-4 fill-brand-gold" />
                  <Star className="w-4 h-4 stroke-brand-gold fill-none" />
                  <span className="text-white ml-1 text-xs">4.1 Star</span>
                </div>
                <p className="text-[11px] font-sans text-zinc-350 italic">
                  &ldquo;That Mysore Masala Dosa melted like pure cloud butter inside my mouth...&rdquo;
                </p>
                <p className="text-[9px] font-semibold text-brand-gold uppercase tracking-wider text-right mt-1">
                  — Google Local Guide
                </p>
              </div>
            </div>
          </div>

        </div>
      </section>

      {/* Key Metrics / Highlights Bento style */}
      <section className="bg-brand-cream py-10 px-4 sm:px-8 border-b border-brand-gold/10">
        <div className="max-w-7xl mx-auto">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-6">
            
            <div className="bg-white p-6 rounded-2xl border border-brand-gold/10 shadow-sm text-center">
              <div className="mx-auto w-10 h-10 bg-brand-gold/10 rounded-full flex items-center justify-center text-brand-gold mb-3">
                <Star className="w-5 h-5 fill-brand-gold" />
              </div>
              <h3 className="font-serif text-3xl font-bold text-brand-forest">4.1</h3>
              <p className="text-xs text-zinc-500 font-semibold tracking-wider uppercase mt-1">Customer Rating</p>
            </div>

            <div className="bg-white p-6 rounded-2xl border border-brand-gold/10 shadow-sm text-center">
              <div className="mx-auto w-10 h-10 bg-brand-forest/10 rounded-full flex items-center justify-center text-brand-forest mb-3">
                <MessageSquare className="w-5 h-5" />
              </div>
              <h3 className="font-serif text-3xl font-bold text-brand-forest">{numReviews}</h3>
              <p className="text-xs text-zinc-500 font-semibold tracking-wider uppercase mt-1">Google Reviews</p>
            </div>

            <div className="bg-white p-6 rounded-2xl border border-brand-gold/10 shadow-sm text-center">
              <div className="mx-auto w-10 h-10 bg-brand-terracotta/10 rounded-full flex items-center justify-center text-brand-terracotta mb-3">
                <Award className="w-5 h-5" />
              </div>
              <h3 className="font-serif text-3xl font-bold text-brand-forest">Rank #1</h3>
              <p className="text-xs text-zinc-500 font-semibold tracking-wider uppercase mt-1">Vegetarian Spot</p>
            </div>

            <div className="bg-white p-6 rounded-2xl border border-brand-gold/10 shadow-sm text-center">
              <div className="mx-auto w-10 h-10 bg-emerald-100 rounded-full flex items-center justify-center text-emerald-700 mb-3">
                <Utensils className="w-5 h-5" />
              </div>
              <h3 className="font-serif text-3xl font-bold text-brand-forest">100%</h3>
              <p className="text-xs text-zinc-500 font-semibold tracking-wider uppercase mt-1">Pure Vegetarian</p>
            </div>

          </div>
        </div>
      </section>

      {/* Interactive Menu Section */}
      <section id="menu-section" className="py-16 sm:py-24 px-4 sm:px-8 bg-zinc-500/5">
        <div className="max-w-7xl mx-auto">
          
          <div className="text-center space-y-3 mb-12">
            <span className="text-brand-terracotta font-serif text-lg italic block">A Taste of Royalty</span>
            <h2 className="font-serif text-3xl sm:text-4xl font-bold text-brand-forest">
              The Heritage Culinary Menu
            </h2>
            <p className="text-zinc-650 max-w-xl mx-auto text-sm sm:text-base">
              Every dish is freshly cooked based on heritage secret spice ratios with premium ghee, crisp local produce, and pure unfiltered hospitality.
            </p>
            
            {/* Category Filter Pills */}
            <div className="flex flex-wrap items-center justify-center gap-2 pt-4">
              {[
                { id: "all", label: "All Masterpieces" },
                { id: "breakfast", label: "Heritage Breakfast" },
                { id: "meals", label: "Traditional Platter / Meals" },
                { id: "sweets-beverages", label: "Sweets & Traditional Coffee" }
              ].map(cat => (
                <button
                  key={cat.id}
                  onClick={() => setSelectedCategory(cat.id)}
                  className={`px-4 py-2 rounded-xl text-xs sm:text-sm font-semibold transition-all cursor-pointer ${
                    selectedCategory === cat.id 
                    ? "bg-brand-forest text-brand-cream border border-brand-gold/40 shadow-md"
                    : "bg-white text-zinc-650 hover:bg-zinc-50 border border-zinc-200"
                  }`}
                >
                  {cat.label}
                </button>
              ))}
            </div>
          </div>

          {/* Menu Items Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {filteredMenuItems.map(item => (
              <div 
                key={item.id}
                className="bg-white border border-brand-gold/10 hover:border-brand-gold/30 rounded-2xl overflow-hidden shadow-sm hover:shadow-lg transition-all flex flex-col group cursor-pointer"
                onClick={() => {
                  setSelectedMenuItem(item);
                  setOrderQuantity(1);
                  setOrderSimulated(false);
                }}
              >
                {/* Image & tag */}
                <div className="relative h-44 overflow-hidden bg-zinc-100">
                  <img 
                    src={item.imageUrl} 
                    alt={item.name} 
                    className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500"
                    referrerPolicy="no-referrer"
                  />
                  <div className="absolute top-3 right-3 bg-white/95 text-brand-forest font-semibold text-xs py-1 px-2.5 rounded-lg border border-brand-gold/20 shadow-sm backdrop-blur-sm">
                    ₹{item.price}
                  </div>
                  
                  {item.spiceLevel && (
                    <div className="absolute bottom-3 left-3 bg-brand-dark/90 text-brand-gold font-semibold text-[10px] py-1 px-2 rounded-lg border border-white/10 flex items-center gap-1 backdrop-blur-sm">
                      {"🌶️".repeat(item.spiceLevel)} Spicy
                    </div>
                  )}
                </div>

                {/* Info */}
                <div className="p-5 flex-1 flex flex-col justify-between space-y-4">
                  <div className="space-y-2">
                    <h3 className="font-serif font-bold text-base text-brand-forest group-hover:text-brand-terracotta transition-colors flex justify-between items-start gap-1">
                      {item.name}
                    </h3>
                    <p className="text-xs text-zinc-600 leading-relaxed line-clamp-2">
                      {item.description}
                    </p>
                  </div>

                  <div className="space-y-3">
                    {/* Tags */}
                    <div className="flex flex-wrap gap-1">
                      {item.tags.map((tag, idx) => (
                        <span key={idx} className="bg-brand-gold/10 text-brand-terracotta text-[9px] font-bold px-2 py-0.5 rounded uppercase tracking-wider">
                          {tag}
                        </span>
                      ))}
                    </div>

                    <div className="pt-2 border-t border-zinc-100 flex items-center justify-between text-xs font-semibold text-brand-forest group-hover:text-brand-terracotta transition-all">
                      <span>View Craft Recipe</span>
                      <Plus className="w-4 h-4 bg-brand-forest/5 text-brand-forest group-hover:bg-brand-terracotta/10 group-hover:text-brand-terracotta rounded-full p-0.5 transition-colors" />
                    </div>
                  </div>
                </div>

              </div>
            ))}
          </div>

        </div>
      </section>

      {/* Menu Detail Slide-over Modal Simulator */}
      <AnimatePresence>
        {selectedMenuItem && (
          <div className="fixed inset-0 bg-brand-dark/65 backdrop-blur-sm z-50 flex items-center justify-center p-4">
            <motion.div 
              initial={{ scale: 0.95, opacity: 0 }}
              animate={{ scale: 1, opacity: 1 }}
              exit={{ scale: 0.95, opacity: 0 }}
              className="bg-brand-cream border-2 border-brand-gold/30 rounded-3xl overflow-hidden max-w-lg w-full shadow-2xl relative block"
              onClick={(e) => e.stopPropagation()}
            >
              {/* Close Button */}
              <button 
                onClick={() => setSelectedMenuItem(null)}
                className="absolute top-4 right-4 bg-brand-cream hover:bg-zinc-150 p-2 rounded-full border border-zinc-350 text-brand-dark transition-colors z-10 cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>

              {/* Header Image */}
              <div className="relative h-56 overflow-hidden">
                <img 
                  src={selectedMenuItem.imageUrl} 
                  alt={selectedMenuItem.name}
                  className="w-full h-full object-cover"
                  referrerPolicy="no-referrer"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-brand-cream via-transparent to-transparent"></div>
                <div className="absolute bottom-4 left-6">
                  <span className="bg-brand-terracotta text-brand-cream text-[10px] font-bold uppercase tracking-widest px-2.5 py-1 rounded inline-block mb-1">
                    {selectedMenuItem.category.replace("-", " & ")}
                  </span>
                  <h3 className="font-serif font-bold text-2xl text-brand-forest text-shadow-sm leading-tight">
                    {selectedMenuItem.name}
                  </h3>
                </div>
              </div>

              {/* Recipe/Craft details */}
              <div className="p-6 space-y-5">
                <div className="flex justify-between items-center bg-white p-3.5 rounded-2xl border border-brand-gold/10">
                  <div className="text-zinc-550 text-xs font-semibold uppercase tracking-wider">Heritage Pricing</div>
                  <div className="font-serif text-2xl font-bold text-brand-forest">₹{selectedMenuItem.price}</div>
                </div>

                <div className="space-y-2">
                  <h4 className="font-serif font-bold text-brand-forest text-sm flex items-center gap-1.5 border-b border-brand-gold/10 pb-1">
                    <Sparkles className="w-4 h-4 text-brand-gold" /> Secrets of the Royal Recipe
                  </h4>
                  <p className="text-xs text-zinc-700 leading-relaxed italic">
                    &ldquo;{selectedMenuItem.craftStory}&rdquo;
                  </p>
                </div>

                <div className="space-y-2">
                  <h4 className="font-serif font-bold text-brand-forest text-sm">Culinary Highlights</h4>
                  <p className="text-xs text-zinc-650 leading-relaxed">
                    {selectedMenuItem.description}
                  </p>
                  <div className="flex flex-wrap gap-1.5 pt-1">
                    {selectedMenuItem.tags.map((tag, i) => (
                      <span key={i} className="bg-emerald-50 text-emerald-700 border border-emerald-100 text-[9px] font-bold uppercase tracking-wider px-2 py-0.5 rounded-md">
                        {tag}
                      </span>
                    ))}
                  </div>
                </div>

                {/* Simulation Order Panel */}
                <div className="bg-white p-4.5 rounded-2xl border border-brand-gold/25 space-y-4">
                  {orderSimulated ? (
                    <div className="text-center py-2 space-y-2">
                      <div className="mx-auto w-10 h-10 bg-emerald-100 rounded-full flex items-center justify-center text-emerald-600">
                        <CheckCircle className="w-6 h-6" />
                      </div>
                      <h4 className="font-bold text-brand-forest text-sm">Simulated Culinary Request Sent!</h4>
                      <p className="text-[11px] text-zinc-650">
                        Since we have <strong>no third-party website listed</strong> on Google Maps, we simulated sending this custom order directly to our express kitchen lobby. 
                      </p>
                      <button 
                        onClick={() => setSelectedMenuItem(null)}
                        className="text-brand-terracotta underline hover:text-brand-terracotta/80 text-xs font-semibold cursor-pointer"
                      >
                        Back to Menu
                      </button>
                    </div>
                  ) : (
                    <div className="space-y-4">
                      <div className="flex items-center justify-between">
                        <div className="text-xs font-bold text-brand-forest">Adjust Servings</div>
                        <div className="flex items-center gap-2">
                          <button 
                            disabled={orderQuantity <= 1}
                            onClick={() => setOrderQuantity(q => q - 1)}
                            className="w-7 h-7 bg-zinc-100 hover:bg-zinc-200 disabled:opacity-50 border border-zinc-200 text-zinc-700 font-bold rounded-lg text-xs cursor-pointer"
                          >
                            -
                          </button>
                          <span className="font-bold text-sm w-4 text-center">{orderQuantity}</span>
                          <button 
                            onClick={() => setOrderQuantity(q => q + 1)}
                            className="w-7 h-7 bg-zinc-100 hover:bg-zinc-200 border border-zinc-200 text-zinc-700 font-bold rounded-lg text-xs cursor-pointer"
                          >
                            +
                          </button>
                        </div>
                      </div>

                      <button
                        onClick={() => setOrderSimulated(true)}
                        className="w-full bg-brand-forest hover:bg-brand-forest/90 text-brand-cream border border-brand-gold/30 font-semibold py-2.5 rounded-xl text-xs transition-colors flex items-center justify-center gap-2 cursor-pointer"
                      >
                        <Utensils className="w-4 h-4" /> Simulate Immediate Kitchen Order • Total: ₹{selectedMenuItem.price * orderQuantity}
                      </button>
                    </div>
                  )}
                </div>

              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>

      {/* Interactive Table Reservations Simulator */}
      <section id="reservations" className="py-16 sm:py-24 px-4 sm:px-8 bg-brand-forest text-brand-cream border-t border-b border-brand-gold/20">
        <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
          
          <div className="lg:col-span-5 space-y-6">
            <span className="text-brand-gold font-serif text-lg italic block">Traditional Hospitality</span>
            <h2 className="font-serif text-3xl sm:text-4xl font-bold tracking-tight">
              Table Reservation Simulator
            </h2>
            <p className="text-zinc-300 text-sm leading-relaxed">
              Mahesh Prasad Veg Restaurant maintains two main dining zones in Mysuru: the majestic <strong className="text-brand-gold">Classic Traditional Hall</strong> and our air-conditioned <strong className="text-brand-gold">AC Royal Lounge</strong>.
            </p>
            <p className="text-zinc-300 text-sm leading-relaxed">
              We never want you to stand in queue at Ballal Circle. Use this simulator to claim a prior reserved desk and watch our system allocate your traditional ticket instantly.
            </p>

            <div className="space-y-4">
              <div className="flex items-start gap-3">
                <div className="p-2 bg-brand-cream/10 border border-white/10 rounded-xl text-brand-gold shrink-0">
                  <MapPin className="w-4 h-4" />
                </div>
                <div className="text-xs">
                  <p className="font-semibold text-white">Ballal Circle Institutional Address</p>
                  <p className="text-zinc-400">Near RTO Office, Chamarajapuram, Mysuru, Karnataka 570005</p>
                </div>
              </div>

              <div className="flex items-start gap-3">
                <div className="p-2 bg-brand-cream/10 border border-white/10 rounded-xl text-brand-gold shrink-0">
                  <Phone className="w-4 h-4" />
                </div>
                <div className="text-xs">
                  <p className="font-semibold text-white">Direct Restaurant Inquiry</p>
                  <p className="text-zinc-400">0821 233 0820 (Call to confirm group banquets)</p>
                </div>
              </div>
            </div>

            {/* Simulated Booking Count display */}
            {allBookings.length > 0 && (
              <div className="pt-4 border-t border-white/10 space-y-3">
                <h4 className="text-xs font-bold uppercase tracking-wider text-brand-gold">Your Simulated Bookings ({allBookings.length})</h4>
                <div className="space-y-2 max-h-48 overflow-y-auto pr-2">
                  {allBookings.map(b => (
                    <div 
                      key={b.id} 
                      className="bg-white/5 border border-white/10 p-3 rounded-xl flex items-center justify-between text-xs transition-colors hover:bg-white/10"
                    >
                      <div>
                        <p className="font-bold text-brand-gold">{b.guestName} ({b.guestsCount} Guests)</p>
                        <p className="text-zinc-400">{b.date} • {b.timeSlot} • <span className="italic">{b.hallType}</span></p>
                        <p className="font-mono text-[9px] text-zinc-500 mt-1 uppercase tracking-widest">Code: {b.bookingCode}</p>
                      </div>
                      <button 
                        onClick={() => handleCancelBooking(b.id)}
                        className="text-red-400 hover:text-red-300 transition-colors text-[10px] font-bold cursor-pointer"
                        title="Cancel this booking"
                      >
                        Cancel
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Booking Form Card */}
          <div className="lg:col-span-7 bg-white text-zinc-900 border border-brand-gold/15 p-6 sm:p-8 rounded-3xl shadow-2xl relative">
            <div className="absolute top-0 right-12 transform -translate-y-1/2 bg-brand-gold text-brand-forest font-bold text-xs py-1 px-4.5 rounded-full border border-brand-gold shadow">
              Instant Generation
            </div>

            <h3 className="font-serif text-xl font-bold text-brand-forest mb-4">Book Your Heritage Table</h3>

            <form onSubmit={handleBookingSubmit} className="space-y-4">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-zinc-700 block">Your Name</label>
                  <div className="relative">
                    <span className="absolute inset-y-0 left-0 pl-3 flex items-center text-zinc-400">
                      <User className="w-4 h-4" />
                    </span>
                    <input 
                      type="text" 
                      required
                      placeholder="e.g. Ramesh Kumar"
                      value={bookingName}
                      onChange={(e) => setBookingName(e.target.value)}
                      className="w-full pl-9 pr-3 py-2 border border-zinc-200 hover:border-brand-gold/40 focus:border-brand-forest focus:ring-1 focus:ring-brand-forest outline-none rounded-xl text-xs transition-colors"
                    />
                  </div>
                </div>

                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-zinc-700 block">Phone Number</label>
                  <div className="relative">
                    <span className="absolute inset-y-0 left-0 pl-3 flex items-center text-zinc-400">
                      <Phone className="w-4 h-4" />
                    </span>
                    <input 
                      type="tel" 
                      required
                      placeholder="e.g. 9876543210"
                      value={bookingPhone}
                      onChange={(e) => setBookingPhone(e.target.value)}
                      className="w-full pl-9 pr-3 py-2 border border-zinc-200 hover:border-brand-gold/40 focus:border-brand-forest focus:ring-1 focus:ring-brand-forest outline-none rounded-xl text-xs transition-colors"
                    />
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-zinc-700 block">Date</label>
                  <div className="relative">
                    <span className="absolute inset-y-0 left-0 pl-3 flex items-center text-zinc-400">
                      <Calendar className="w-4 h-4" />
                    </span>
                    <input 
                      type="date" 
                      required
                      value={bookingDate}
                      onChange={(e) => setBookingDate(e.target.value)}
                      className="w-full pl-9 pr-3 py-2 border border-zinc-200 hover:border-brand-gold/40 focus:border-brand-forest focus:ring-1 focus:ring-brand-forest outline-none rounded-xl text-xs transition-colors"
                    />
                  </div>
                </div>

                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-zinc-700 block">Preferred Hour</label>
                  <div className="relative">
                    <span className="absolute inset-y-0 left-0 pl-3 flex items-center text-zinc-400">
                      <Clock className="w-4 h-4" />
                    </span>
                    <select 
                      value={bookingTime}
                      onChange={(e) => setBookingTime(e.target.value)}
                      className="w-full pl-9 pr-3 py-2 bg-white border border-zinc-200 hover:border-brand-gold/40 focus:border-brand-forest focus:ring-1 focus:ring-brand-forest outline-none rounded-xl text-xs transition-colors"
                    >
                      <option>7:30 AM</option>
                      <option>9:00 AM</option>
                      <option>12:30 PM</option>
                      <option>2:00 PM</option>
                      <option>5:30 PM</option>
                      <option>7:30 PM</option>
                      <option>9:00 PM</option>
                    </select>
                  </div>
                </div>

                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-zinc-700 block">Number of Guests</label>
                  <div className="relative">
                    <span className="absolute inset-y-0 left-0 pl-3 flex items-center text-zinc-400">
                      <Users className="w-4 h-4" />
                    </span>
                    <input 
                      type="number" 
                      min="1" 
                      max="15" 
                      required
                      value={bookingCount}
                      onChange={(e) => setBookingCount(parseInt(e.target.value) || 2)}
                      className="w-full pl-9 pr-3 py-2 border border-zinc-200 hover:border-brand-gold/40 focus:border-brand-forest focus:ring-1 focus:ring-brand-forest outline-none rounded-xl text-xs transition-colors"
                    />
                  </div>
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-zinc-700 block">Select Dining Area</label>
                  <div className="grid grid-cols-2 gap-3">
                    <button
                      type="button"
                      onClick={() => setBookingHall("Classic Dining")}
                      className={`py-2 px-3 rounded-xl border text-xs font-semibold text-center transition-all cursor-pointer ${
                        bookingHall === "Classic Dining"
                        ? "bg-brand-forest text-brand-cream border-brand-gold shadow"
                        : "bg-zinc-50 text-zinc-600 border-zinc-200 hover:bg-zinc-100"
                      }`}
                    >
                      Classic traditional
                    </button>
                    <button
                      type="button"
                      onClick={() => setBookingHall("AC Royal Hall")}
                      className={`py-2 px-3 rounded-xl border text-xs font-semibold text-center transition-all cursor-pointer ${
                        bookingHall === "AC Royal Hall"
                        ? "bg-brand-forest text-brand-cream border-brand-gold shadow"
                        : "bg-zinc-50 text-zinc-600 border-zinc-200 hover:bg-zinc-100"
                      }`}
                    >
                      AC Royal Lounge
                    </button>
                  </div>
                </div>

                <div className="space-y-1.5">
                  <label className="text-xs font-bold text-zinc-700 block">Dietary Note / Specialty (Optional)</label>
                  <textarea 
                    placeholder="e.g. Birthdays celebration, Jain food only option"
                    value={bookingRequest}
                    onChange={(e) => setBookingRequest(e.target.value)}
                    rows={1}
                    className="w-full px-3 py-2 border border-zinc-200 hover:border-brand-gold/40 focus:border-brand-forest focus:ring-1 focus:ring-brand-forest outline-none rounded-xl text-xs transition-colors resize-none"
                  ></textarea>
                </div>
              </div>

              <button 
                type="submit"
                className="w-full bg-brand-terracotta hover:bg-brand-terracotta/90 text-brand-cream border border-brand-gold/25 font-semibold py-3 rounded-xl text-sm transition-colors mt-2 cursor-pointer"
              >
                Send Table Simulation Request
              </button>
            </form>

            {/* Live Success Ticket Display */}
            {bookingSuccess && (
              <motion.div 
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                className="mt-6 bg-brand-cream border-2 border-dashed border-brand-gold p-5 rounded-2xl space-y-4 text-zinc-900"
              >
                <div className="flex justify-between items-start border-b border-brand-gold/20 pb-3">
                  <div>
                    <h4 className="font-serif font-bold text-brand-forest text-base flex items-center gap-1.5">
                      <CheckCircle className="w-5 h-5 text-emerald-600" /> Confirmed Lounge Code Allocated
                    </h4>
                    <p className="text-[10px] text-zinc-500 mt-0.5">Please take a screenshot of this simulation ticket.</p>
                  </div>
                  <span className="bg-emerald-100 text-emerald-800 text-[10px] font-bold px-2 py-1 rounded-md uppercase">
                    {bookingSuccess.status}
                  </span>
                </div>

                <div className="grid grid-cols-2 gap-4 text-xs">
                  <div>
                    <span className="text-zinc-500 block uppercase tracking-wider text-[9px] font-bold">Lounge Guest</span>
                    <strong className="text-brand-forest text-[13px]">{bookingSuccess.guestName}</strong>
                  </div>
                  <div>
                    <span className="text-zinc-500 block uppercase tracking-wider text-[9px] font-bold">Lounge Desk Code</span>
                    <strong className="font-mono text-[13px] text-brand-terracotta font-bold uppercase">{bookingSuccess.bookingCode}</strong>
                  </div>
                  <div>
                    <span className="text-zinc-500 block uppercase tracking-wider text-[9px] font-bold">Schedule</span>
                    <span className="text-zinc-700">{bookingSuccess.date} @ {bookingSuccess.timeSlot}</span>
                  </div>
                  <div>
                    <span className="text-zinc-500 block uppercase tracking-wider text-[9px] font-bold">Section (Guests)</span>
                    <span className="text-zinc-700">{bookingSuccess.hallType} ({bookingSuccess.guestsCount} Pax)</span>
                  </div>
                </div>

                <div className="bg-white border border-brand-gold/10 p-3 rounded-xl flex items-center gap-3">
                  <div className="shrink-0 bg-zinc-100 p-1.5 rounded-lg border border-zinc-200">
                    <span className="font-mono text-[9px] text-zinc-400 block select-none">QR SIM</span>
                    <div className="w-12 h-12 bg-zinc-805 flex flex-wrap p-0.5 cursor-help">
                      {Array.from({ length: 16 }).map((_, i) => (
                        <div key={i} className={`w-3 h-3 ${i % 3 === 0 || i % 5 === 2 ? 'bg-white' : 'bg-black'}`}></div>
                      ))}
                    </div>
                  </div>
                  <div className="text-[10px] text-zinc-650 leading-relaxed">
                    Simply show this voucher code <strong>{bookingSuccess.bookingCode}</strong> at Mahesh Prasad RTO Road check point in Mysuru. Your dining hall is reserved.
                  </div>
                </div>
                
                <div className="text-right">
                  <button 
                    onClick={() => setBookingSuccess(null)}
                    className="text-brand-forest font-semibold text-xs hover:underline cursor-pointer"
                  >
                    Close Voucher &amp; Make Another Booking
                  </button>
                </div>
              </motion.div>
            )}

          </div>

        </div>
      </section>

      {/* Real Reviews & Verification Section */}
      <section id="reviews-section" className="py-16 sm:py-24 px-4 sm:px-8 bg-white border-b border-brand-gold/10">
        <div className="max-w-7xl mx-auto">
          
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-12">
            
            <div className="lg:col-span-5 space-y-6">
              <span className="text-brand-terracotta font-serif text-lg italic block">Real Customer Stories</span>
              <h2 className="font-serif text-3xl sm:text-4xl font-bold tracking-tight text-brand-forest">
                The Food Speaks for Itself
              </h2>
              <p className="text-zinc-650 text-sm leading-relaxed">
                With over <strong className="text-brand-forest font-semibold">3,914 real public Google reviews</strong> and a rating of <strong className="text-brand-forest font-semibold">4.1 Stars</strong>, Mahesh Prasad Veg Restaurant has maintained deep respect around Mysuru’s families for decades.
              </p>

              {/* Rating statistics block */}
              <div className="bg-brand-cream border border-brand-gold/20 p-6 rounded-2xl space-y-4">
                <div className="flex items-center gap-4">
                  <h3 className="font-serif text-5xl font-bold text-brand-forest">{avgRating}</h3>
                  <div>
                    <div className="flex items-center gap-0.5 text-brand-gold">
                      {Array.from({ length: 5 }).map((_, i) => (
                        <Star key={i} className={`w-5 h-5 ${i < Math.floor(avgRating) ? 'fill-brand-gold' : 'stroke-brand-gold fill-none'}`} />
                      ))}
                    </div>
                    <p className="text-xs text-zinc-500 font-semibold tracking-wider mt-1 uppercase">Average from {numReviews} Guests</p>
                  </div>
                </div>

                {/* Rating bars */}
                <div className="space-y-2 text-xs">
                  <div className="flex items-center justify-between text-zinc-655">
                    <span className="w-12 font-semibold">5 Stars</span>
                    <div className="flex-1 mx-3 h-2 bg-zinc-200 rounded-full overflow-hidden">
                      <div className="bg-brand-forest h-full" style={{ width: "65%" }}></div>
                    </div>
                    <span className="w-8 text-right font-medium">65%</span>
                  </div>
                  <div className="flex items-center justify-between text-zinc-655">
                    <span className="w-12 font-semibold">4 Stars</span>
                    <div className="flex-1 mx-3 h-2 bg-zinc-200 rounded-full overflow-hidden">
                      <div className="bg-brand-gold h-full" style={{ width: "22%" }}></div>
                    </div>
                    <span className="w-8 text-right font-medium">22%</span>
                  </div>
                  <div className="flex items-center justify-between text-zinc-655">
                    <span className="w-12 font-semibold">3 Stars</span>
                    <div className="flex-1 mx-3 h-2 bg-zinc-200 rounded-full overflow-hidden">
                      <div className="bg-brand-gold h-full" style={{ width: "8%" }}></div>
                    </div>
                    <span className="w-8 text-right font-medium">8%</span>
                  </div>
                  <div className="flex items-center justify-between text-zinc-655">
                    <span className="w-12 font-semibold">2 Stars</span>
                    <div className="flex-1 mx-3 h-2 bg-zinc-200 rounded-full overflow-hidden">
                      <div className="bg-brand-gold h-full" style={{ width: "3%" }}></div>
                    </div>
                    <span className="w-8 text-right font-medium">3%</span>
                  </div>
                  <div className="flex items-center justify-between text-zinc-655">
                    <span className="w-12 font-semibold">1 Star</span>
                    <div className="flex-1 mx-3 h-2 bg-zinc-200 rounded-full overflow-hidden">
                      <div className="bg-red-400 h-full" style={{ width: "2%" }}></div>
                    </div>
                    <span className="w-8 text-right font-medium">2%</span>
                  </div>
                </div>
              </div>

              {/* Form poster block */}
              <div className="bg-zinc-100/60 p-6 rounded-2xl border border-zinc-200">
                <h4 className="font-serif font-semibold text-brand-forest text-sm mb-3">Add Your Verified Review</h4>
                <form onSubmit={handleReviewSubmit} className="space-y-3.5">
                  <div className="grid grid-cols-2 gap-3">
                    <div className="space-y-1">
                      <label className="text-[10px] font-bold text-zinc-600 block">Name</label>
                      <input 
                        type="text" 
                        required 
                        placeholder="e.g. Chethan Gowda"
                        value={reviewName}
                        onChange={(e) => setReviewName(e.target.value)}
                        className="w-full px-3 py-1.5 border border-zinc-200 bg-white focus:border-brand-forest focus:ring-1 focus:ring-brand-forest outline-none rounded-xl text-xs"
                      />
                    </div>
                    <div className="space-y-1">
                      <label className="text-[10px] font-bold text-zinc-600 block">Star Rating</label>
                      <select
                        value={reviewRating}
                        onChange={(e) => setReviewRating(parseInt(e.target.value) || 5)}
                        className="w-full px-3 py-1.5 border border-zinc-200 bg-white focus:border-brand-forest focus:ring-1 focus:ring-brand-forest outline-none rounded-xl text-xs cursor-pointer"
                      >
                        <option value="5">⭐⭐⭐⭐⭐ Excellent (5)</option>
                        <option value="4">⭐⭐⭐⭐ Great (4)</option>
                        <option value="3">⭐⭐⭐ Good (3)</option>
                        <option value="2">⭐⭐ Fair (2)</option>
                        <option value="1">⭐ Poor (1)</option>
                      </select>
                    </div>
                  </div>
                  
                  <div className="space-y-1">
                    <label className="text-[10px] font-bold text-zinc-600 block">Your Culinary Review</label>
                    <textarea
                      required
                      rows={2}
                      placeholder="Comment on your favorite South Indian food item..."
                      value={reviewComment}
                      onChange={(e) => setReviewComment(e.target.value)}
                      className="w-full px-3 py-1.5 border border-zinc-200 bg-white focus:border-brand-forest focus:ring-1 focus:ring-brand-forest outline-none rounded-xl text-xs resize-none"
                    ></textarea>
                  </div>

                  <button 
                    type="submit"
                    className="w-full bg-brand-forest hover:bg-brand-forest/95 text-brand-cream text-xs font-semibold py-2 rounded-xl transition-all border border-brand-gold/20 flex items-center justify-center gap-1.5 cursor-pointer"
                  >
                    <MessageCircle className="w-3.5 h-3.5" /> Post verified review
                  </button>
                </form>

                {reviewSuccessMessage && (
                  <motion.div 
                    initial={{ opacity: 0, y: 5 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="mt-3 bg-emerald-55 text-emerald-900 border border-emerald-200 p-2 text-[10px] rounded-lg font-bold text-center animate-bounce"
                  >
                    {reviewSuccessMessage}
                  </motion.div>
                )}
              </div>

            </div>

            {/* List of customer voice blocks */}
            <div className="lg:col-span-7 space-y-6">
              <h3 className="font-serif text-lg font-bold text-brand-forest flex items-center gap-2">
                <Quote className="w-5 h-5 text-brand-gold" /> Honest Guest Testimonials
              </h3>

              <div className="space-y-4">
                {reviewsList.map(review => (
                  <div 
                    key={review.id}
                    className="bg-brand-cream border border-brand-gold/15 p-5 rounded-2xl relative shadow-xs transition-all hover:bg-white hover:border-brand-gold/30 hover:shadow"
                  >
                    {review.verified && (
                      <span className="absolute top-4 right-4 bg-emerald-50 text-emerald-700 font-bold text-[9px] uppercase tracking-wider py-0.5 px-2 rounded-full border border-emerald-100 flex items-center gap-1 leading-none">
                        <CheckCircle className="w-3 h-3 text-emerald-600" /> Verified Dine-in
                      </span>
                    )}

                    <div className="flex items-center gap-3 mb-3">
                      <div className="w-9 h-9 bg-brand-forest/10 rounded-full flex items-center justify-center font-bold text-brand-forest text-sm">
                        {review.userName[0]}
                      </div>
                      <div>
                        <h4 className="font-serif font-bold text-brand-forest text-sm">{review.userName}</h4>
                        <div className="flex items-center gap-1">
                          <div className="flex text-brand-gold">
                            {Array.from({ length: 5 }).map((_, i) => (
                              <Star key={i} className={`w-3 h-3 ${i < review.rating ? 'fill-brand-gold' : 'stroke-brand-gold fill-none'}`} />
                            ))}
                          </div>
                          <span className="text-[10px] text-zinc-400 font-medium ml-1">• {review.date}</span>
                        </div>
                      </div>
                    </div>

                    <p className="text-xs text-zinc-700 leading-relaxed italic mb-4">
                      &ldquo;{review.comment}&rdquo;
                    </p>

                    <div className="flex items-center justify-between border-t border-brand-gold/10 pt-3 text-[10px] text-zinc-500 font-semibold">
                      <span>Source: Google Maps Local Review</span>
                      <button 
                        onClick={() => handleLikeReview(review.id)}
                        className="flex items-center gap-1 hover:text-brand-terracotta text-brand-forest transition-colors font-bold cursor-pointer"
                      >
                        <ThumbsUp className="w-3.5 h-3.5" /> Awesome review ({review.likes})
                      </button>
                    </div>

                  </div>
                ))}
              </div>
            </div>

          </div>

        </div>
      </section>

      {/* Interactive FAQ, Hours and Parking */}
      <section className="py-16 sm:py-20 px-4 sm:px-8 bg-zinc-50 border-b border-brand-gold/10">
        <div className="max-w-7xl mx-auto">
          
          <div className="max-w-3xl mx-auto space-y-8">
            
            <div className="text-center space-y-2">
              <span className="text-brand-terracotta font-serif text-base block italic">Frequently Asked Queries</span>
              <h2 className="font-serif text-3xl font-bold text-brand-forest">Inside Mahesh Prasad</h2>
              <p className="text-xs text-zinc-500 font-bold uppercase tracking-widest pt-1">Everything You Need To Know</p>
            </div>

            <div className="space-y-4">
              
              <div className="bg-white border border-brand-gold/10 p-5 rounded-2xl shadow-xs">
                <h4 className="font-serif font-bold text-brand-forest text-sm sm:text-base">📍 Where is Mahesh Prasad Veg Restaurant located in Mysuru?</h4>
                <p className="text-xs sm:text-sm text-zinc-600 leading-relaxed mt-2 pl-3 border-l-2 border-brand-gold">
                  We are conveniently situated directly at <strong>Ballal Circle (near RTO Office)</strong>, Chamarajapura, Chamarajapuram Mohalla, Lakshmipuram, Mysuru, Karnataka 570005. It is a highly central location easily accessible by rickshaw or bus.
                </p>
              </div>

              <div className="bg-white border border-brand-gold/10 p-5 rounded-2xl shadow-xs">
                <h4 className="font-serif font-bold text-brand-forest text-sm sm:text-base">☕ What are your absolute must-try specialties?</h4>
                <p className="text-xs sm:text-sm text-zinc-605 leading-relaxed mt-2 pl-3 border-l-2 border-brand-gold">
                  Our regular guests swear by the legendary <strong>Mysore Masala Dosa</strong> (cooked with aromatic pure ghee), pillowy soft **Rava Idli**, crunchy savory **Uddin Vada**, and our signature gold-tinted brass **Filter Coffee**.
                </p>
              </div>

              <div className="bg-white border border-brand-gold/10 p-5 rounded-2xl shadow-xs">
                <h4 className="font-serif font-bold text-brand-forest text-sm sm:text-base">🚗 Is there customer parking available?</h4>
                <p className="text-xs sm:text-sm text-zinc-605 leading-relaxed mt-2 pl-3 border-l-2 border-brand-gold">
                  Two-wheeler parking is easily available directly in adjacent lanes. For four-wheelers, side-street parking is open near the RTO office, though peak hours (9:00 AM breakfast and 1:30 PM meal rush) get highly crowded.
                </p>
              </div>

              <div className="bg-white border border-brand-gold/10 p-5 rounded-2xl shadow-xs">
                <h4 className="font-serif font-bold text-brand-forest text-sm sm:text-base">🌐 Why has no official website been shown on Google Maps?</h4>
                <p className="text-xs sm:text-sm text-zinc-650 leading-relaxed mt-2 pl-3 border-l-2 border-brand-gold">
                  Mahesh Prasad is a highly traditional, locally rooted business with over 3,900 glowing customer testimonials. We prioritize top-quality fresh daily cooking rather than maintaining websites, which is why we created this beautiful representation page to assist visitors!
                </p>
              </div>

            </div>

          </div>

        </div>
      </section>

      {/* Footer Section presenting original data */}
      <footer className="bg-brand-dark text-zinc-400 py-16 px-4 sm:px-8">
        <div className="max-w-7xl mx-auto space-y-12">
          
          <div className="grid grid-cols-1 md:grid-cols-12 gap-8 items-start">
            
            <div className="md:col-span-4 space-y-4">
              <div className="flex items-center gap-3">
                <div className="bg-white/10 text-brand-gold h-10 w-10 rounded-xl flex items-center justify-center font-serif text-lg font-bold border border-white/10">
                  M
                </div>
                <div>
                  <h3 className="font-serif text-lg font-bold text-white tracking-tight">Mahesh Prasad</h3>
                  <p className="text-[10px] font-semibold text-brand-gold uppercase tracking-wider">Traditional Veg Restaurant</p>
                </div>
              </div>
              <p className="text-xs text-zinc-400 leading-relaxed">
                Celebrating the pure rich vegetarian lineage of Mysuru. Authentic recipes, pristine ingredients, and traditional hospitality from Ballal Circle.
              </p>
            </div>

            <div className="md:col-span-8 grid grid-cols-1 sm:grid-cols-3 gap-8">
              
              <div className="space-y-3.5">
                <h4 className="text-xs font-bold uppercase tracking-widest text-white border-b border-white/10 pb-1.5">Direct Contacts</h4>
                <ul className="space-y-2 text-xs">
                  <li>
                    <span className="text-zinc-500 block">Phone Support</span>
                    <a href="tel:08212330820" className="text-white hover:text-brand-gold font-medium">0821 233 0820</a>
                  </li>
                  <li>
                    <span className="text-zinc-500 block">Location Area</span>
                    <span className="text-zinc-300">Ballal Circle, Near RTO Office, Chamarajapura, Mysuru</span>
                  </li>
                </ul>
              </div>

              <div className="space-y-3.5">
                <h4 className="text-xs font-bold uppercase tracking-widest text-white border-b border-white/10 pb-1.5">Operating Hours</h4>
                <ul className="space-y-2 text-xs">
                  <li className="flex justify-between">
                    <span>Monday — Sunday</span>
                    <strong className="text-brand-gold">6:30 AM - 10:30 PM</strong>
                  </li>
                  <li className="flex justify-between">
                    <span>Breakfast Service</span>
                    <span className="text-zinc-300">6:30 AM - 11:30 AM</span>
                  </li>
                  <li className="flex justify-between">
                    <span>Royal Meals Platter</span>
                    <span className="text-zinc-300">12:15 PM - 3:30 PM</span>
                  </li>
                </ul>
              </div>

              <div className="space-y-3.5">
                <h4 className="text-xs font-bold uppercase tracking-widest text-white border-b border-white/10 pb-1.5">Google Metadata</h4>
                <ul className="space-y-2 text-xs">
                  <li>
                    <span className="text-zinc-500 block">Public Rank</span>
                    <strong className="text-brand-gold">Rank #1 Best Family Spot</strong>
                  </li>
                  <li>
                    <span className="text-zinc-500 block">Found via search query</span>
                    <span className="text-zinc-350 italic">&ldquo;restaurant in Mysuru&rdquo;</span>
                  </li>
                  <li>
                    <a 
                      href="https://www.google.com/maps/search/?api=1&query_place_id=ChIJ776TqABwrzsRJlFuzZSXo-I&query=Mahesh%20Prasad%20Veg%2520Restaurant"
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-brand-gold hover:underline flex items-center gap-1 text-[11px]"
                    >
                      Open official Google Map <ExternalLink className="w-3 h-3" />
                    </a>
                  </li>
                </ul>
              </div>

            </div>

          </div>

          <div className="border-t border-white/10 pt-8 flex flex-col sm:flex-row justify-between items-center text-[10px] text-zinc-500 gap-4">
            <p>© 2026 Mahesh Prasad Veg Restaurant, Mysuru. Beautifully replicated with modern UI assets. All rights reserved.</p>
            <div className="flex gap-4">
              <span>Pure Vegetarian Certify</span>
              <span>•</span>
              <span>Ballal Circle landmark</span>
            </div>
          </div>

        </div>
      </footer>

    </div>
  );
}
